name: BarkPanel
version: 1.0-Beta8
description: Adds a web panel to a minecraft server.
author: rymate1234
load: STARTUP

main: net.rymate.jpanel.PanelPlugin
softdepend: [Vault]

commands:
  barkpanel:
    description: Information about the current BarkPanel install
    usage: /<command>
  addlogin:
    description: Adds a user to BarkPanel
    usage: /<command> [username] [password]
  passwd:
    description: Change the password for a BarkPanel user
    usage: /<command> [username] [oldpassword] [newpassword]
